function [mask, LocalWindows, ColorModels, ShapeConfidences] = ...
    updateModels(...
        NewLocalWindows, ...
        LocalWindows, ...
        CurrentFrame, ...
        warpedMask, ...
        warpedMaskOutline, ...
        WindowWidth, ...
        ColorModels, ...
        ShapeConfidences, ...
        ProbMaskThreshold, ...
        fcutoff, ...
        SigmaMin, ...
        R, ...
        A, ...
        Fore_prob ...
    )
% UPDATEMODELS: update shape and color models, and apply the result to generate a new mask.
% Feel free to redefine this as several different functions if you prefer.
%hint: update based on area of new foreground mask

s = size(LocalWindows, 1);
new_fore_prob = cell(1,s);
for i = 1:s
    new_fore_prob = ShapeConfidences{1,i}.*warpedMask+ (1-ShapeConfidences{1,i}).*Fore_prob{1,i};
end

